### ISSUE TITLE
target_hash not carried over when choosing to edit an existing lexeme

### ISSUE THREAD

**Issue by jhsoby** [lucaswerkmeister/tool-lexeme-forms#142]
Steps to reproduce:
1. Go to a lexeme form with forms pre-filled and a target_hash value in the URL, like this: https://lexeme-forms.toolforge.org/template/bokm%C3%A5l-adverb/?form_representation=hjem&target_hash=mytest
2. Press to edit the existing adverb (L740778)
3. Press save
4. Observe that the given target_hash is not present when you are redirected to Wikidata

Compare this to:
1. Visiting https://lexeme-forms.toolforge.org/template/bokm%C3%A5l-adverb/edit/L740778?form_representation=hjem&target_hash=mytest
2. Pressing save
3. Observe that the given hash *is* present when you are redirected to Wikidata

**Comment by lucaswerkmeister** [comment]
Should be fixed now, can you try it out?
