### ISSUE TITLE
Prefill all forms automatically

### ISSUE THREAD

**Issue by egils-consulting** [lucaswerkmeister/tool-lexeme-forms#15]
For example when coming from an english noun only the first box for singular is prefilled.
I would like the plural prefilled with the same + the most common ending in this case "s"

**Comment by lucaswerkmeister** [comment]
This has been discussed and rejected before. I will not add any form generation to the tool; instead, the tool has several features to let you generate forms and use them with the tool. See [Wikidata:Wikidata Lexeme Forms § Automatically generating forms](https://www.wikidata.org/wiki/Wikidata:Wikidata_Lexeme_Forms#Automatically_generating_Forms).
