### ISSUE TITLE
Working on local development setup

### ISSUE THREAD

**Issue by bennylin** [lucaswerkmeister/tool-lexeme-forms#174]
The doc indicated: `You can also run the tool locally, which is much more convenient for development (for example, Flask will automatically reload the application any time you save a file). Note that a local setup will not actually perform edits unless you create a config.yaml file.` and I have config.yaml file, but it's not possible to login / authenticate from local development setup. How to perform the actual edits on local development setup? Thanks.

**Comment by lucaswerkmeister** [comment]
You’ll need to request your own OAuth consumer (like [this one](https://meta.wikimedia.org/wiki/Special:OAuthListConsumers/view/fb188b77c1c3c3103f113f6e2d8bb1c4)) and put that in the config file.

**Comment by bennylin** [comment]
OK. Thanks!
