### ISSUE TITLE
Support generating forms from lemma in edit mode

### ISSUE THREAD

**Issue by nikkiwd** [lucaswerkmeister/tool-lexeme-forms#199]
It would be nice if the Wikifunctions support could also generate forms from the lemma when in edit mode.

e.g. I tried to generate the forms on https://lexeme-forms.toolforge.org/template/german-noun-neuter/edit/L920655 but nothing happened.

**Comment by lucaswerkmeister** [comment]
That should be supported (since 91cc7061cf) and just worked for me on the page you linked; are you sure you waited long enough? (Cf. #198.)l

**Comment by nikkiwd** [comment]
I tried again and I don't see any network requests being made.

Looking at wikifunctions.js, I don't see any special handling of the lemma on edit pages. Did you manually copy the lemma to the first form or something?

**Comment by lucaswerkmeister** [comment]
I guess I did, yeah – I didn’t realize that was the part you meant was missing.

**Comment by lucaswerkmeister** [comment]
This should work now.
