### ISSUE TITLE
Lexeme-forms on Toolforge returns error

### ISSUE THREAD

**Issue by fnielsen** [lucaswerkmeister/tool-lexeme-forms#226]
Also reported at https://phabricator.wikimedia.org/T374344 (I am unsure where the canonical issue tracker is!?)

Steps to replicate the issue (include links if applicable):

https://lexeme-forms.toolforge.org/template/danish-adjective/?form_representation=milj%C3%B8bevidst

What happens?:

    Internal Server Error

    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

What should have happened instead?:
No error. A webpage should show.

**Comment by lucaswerkmeister** [comment]
Closing per Phabricator.
