### ISSUE TITLE
Load User:$username/LexemeForms.js

### ISSUE THREAD

**Issue by jhsoby** [lucaswerkmeister/tool-lexeme-forms#34]
I would love it if the tool could load a JavaScript page from Wikidata so that you can amend the tool's content in various ways. My specific usecase is that I have a script on Wikidata that adds an iframe with the official Norwegian dictionary to lexeme pages. The place where it would be most useful, however, is in lexeme-forms, because the dictionary gives information about the correct inflection of words. So if the tool could load the logged-in user's /LexemeForms.js page from Wikidata, that would enable me to add the same iframe to the tool as well, saving me from opening another tab with the dictionary to check the correct inflection.

There may be like a zillion reasons why this may be a bad idea, but maybe–just maaybe–it could work? :grin:

**Comment by lucaswerkmeister** [comment]
I mean, I don’t think it’s a question of it it <em>can</em> work – technically, it should be pretty simple. The question is I’m comfortable allowing this? And I think my answer is no. Allowing tool userscripts would mean I have to consider the impact on these scripts with each change I make to the tool (is this change going to break a script? when I add this new feature, what will scripts that are not expecting it do?), and on each incoming bug report I also have to check if the result might have been affected by a user script. I don’t think I can commit to that amount of extra work.

For your dictionary usecase, I imagine you could use some browser extension (is Greasemonkey still the standard one? I wouldn’t know), at your own risk, of course.
