### ISSUE TITLE
Add more information/context to the page titles

### ISSUE THREAD

**Issue by nikkiwd** [lucaswerkmeister/tool-lexeme-forms#50]
At the moment all pages have "Wikidata Lexeme Forms" as the page title. This makes it hard to distinguish pages when you have multiple tabs open or when looking at the browser history.

I would particularly like the lemma passed in via the form_representation parameter to be in the title, since I frequently open multiple prefilled forms at once when creating lexemes.

My suggestion is "lemma (ID) – template name (mode) – Wikidata Lexeme Forms"

Examples of how it would look for different pages:

Initial page:
* "deutsches Verb (erstellen) – Wikidata Lexeme Forms" (no lemma)
* "verbieren – deutsches Verb (erstellen) – Wikidata Lexeme Forms" (with lemma)

Advanced mode:
* "deutsches Verb (erweiterter Modus) – Wikidata Lexeme Forms" (no lemma or ID)
* "verbieren – deutsches Verb (erweiterter Modus) – Wikidata Lexeme Forms" (lemma but no ID)
* "verbieren (L123456) – deutsches Verb (erweiterter Modus) – Wikidata Lexeme Forms" (lemma and ID)
* "L123456 – deutsches Verb (erweiterter Modus) – Wikidata Lexeme Forms" (ID but no lemma)

Edit mode:
* "verbieren (L123456) – deutsches Verb (bearbeiten) – Wikidata Lexeme Forms"

Bulk mode:
* "deutsches Verb (Massen-Modus) – Wikidata Lexeme Forms"

**Comment by nikkiwd** [comment]
I'm now using this locally to set the title, let's see what I think in practice.
```
let h1 = document.querySelectorAll("h1")[0]?.innerText;
let h2 = document.querySelectorAll("h2")[0]?.innerText;
let form1 = document.querySelectorAll("input[name='form_representation']")[0]?.value;
let title = document.title;

if (document.location.pathname == "/") {
	// No need to update the index page
} else if (document.location.pathname.endsWith("/bulk/")) {
	title = h1 + " (" + h2 + ") – " + title;
} else if (document.location.pathname.endsWith("/advanced/")) {
	title = (form1 ? form1 + " – " : "") + h1 + " (advanced) – " + title;
} else if (document.location.pathname.endsWith("/edit/")) {
	title = h2 + h1 + " (edit) – " + title;
} else {
	title = (form1 ? form1 + " – " : "") + h1 + " (create) – " + title;
}

document.title = title;
```

**Comment by lucaswerkmeister** [comment]
Hm, but how should the title be tagged?

```html
<title lang=en>deutsches Verb (erstellen) – Wikidata Lexeme Forms</title>
```

```html
<title lang=de>deutsches Verb (erstellen) – Wikidata Lexeme Forms</title>
```

```html
<title lang=mul>deutsches Verb (erstellen) – Wikidata Lexeme Forms</title>
```

**Comment by lucaswerkmeister** [comment]
Probably the template language, since that’s the majority of the title, including the most important / dynamic parts…

**Comment by lucaswerkmeister** [comment]
FIxed server-side (and deployed) – I think I’ll leave out client-side updates for now, since they don’t seem especially useful to me and could even be potentially distracting or disruptive.
