### ISSUE TITLE
Add a link to create a new lexeme when encountering a duplicate in bulk mode

### ISSUE THREAD

**Issue by nikkiwd** [lucaswerkmeister/tool-lexeme-forms#51]
When encountering a possible duplicate in bulk mode, there is a link to edit the duplicate, but there is no convenient way to continue adding the lexeme when it's not a duplicate. You have to navigate to the page for adding an individual word yourself and then enter it all again there.

In bulk mode, it would therefore be useful to have a link at the bottom of the duplicate message for creating a new lexeme, which would open that page prefilled with the forms you already provided.

**Comment by lucaswerkmeister** [comment]
Would a link to the template with a bunch of `&form_representation` be enough (and you’d still have to check the “not a duplicate” box at the bottom)?

Another option would be to add a button that directly POSTs to that form and creates the lexeme immediately. (But you couldn’t open that in a new tab.)

**Comment by nikkiwd** [comment]
Opening the form to submit it manually is what I had in mind. Ideally it would tick the not a duplicate box for you since you already saw the duplicate message, but it's mainly about not having to re-enter the data, so I'd be ok with it not ticking it.

I'd rather not have buttons. I'm pretty sure there is a key combo I can press to submit a form to a new tab, but I can never remember what it is, so I would be worried about clicking it, it not opening in a new tab and then not being sure if I can go back without it resubmitting my batch.

**Comment by lucaswerkmeister** [comment]
Hm, an automated “not a duplicate” tick would have to be guarded by some kind of token – I don’t want others to be able to link to a page with form representations and the checkbox already checked. But a simple link should be straightforward.
