### ISSUE TITLE
Support passing data through Lexeme Forms to the newly-created lexeme

### ISSUE THREAD

**Issue by nikkiwd** [lucaswerkmeister/tool-lexeme-forms#54]
When prefilling fields, there is often extra information we already have that we want to add to the lexeme, e.g. external identifiers. Lexeme Forms only supports adding forms and there is no plan to change that, therefore it would be nice if Lexeme Forms would support passing some data through unchanged in some way which could then be used by scripts on-wiki.

My suggestion would be a parameter which appends its value as the hash when loading the newly-created lexeme, e.g. `/template/language-pos/?form_representation=form1&append=mydata` → `/wiki/Lexeme:L123456#mydata`

**Comment by lucaswerkmeister** [comment]
Hm, that sounds acceptable to me, but why a hash? To me a URL parameter would make more sense: `/template/X/?extra=ABC` → `/wiki/Lexeme:X?lexeme-forms-extra=ABC`

(I guess one reason would be that the tool currently links/redirects to the `/entity/` URI, and the redirect from there to the lexeme page doesn’t preserve arbitrary URL parameters – but I would just fix that by pointing directly to the page URL. I don’t think there’s actually a good reason to link/redirect to the URI.)

**Comment by lucaswerkmeister** [comment]
Hm, on the other hand – for the redirect case, we currently use HTTP 303, which [Wikipedia](https://en.wikipedia.org/w/index.php?title=List_of_HTTP_status_codes&oldid=1025066275#3xx_redirection) describes as:

> The response to the request can be found under another URI using the GET method. When received in response to a POST (or PUT/DELETE), the client should presume that the server has received the data and should issue a new GET request to the given URI.

So maybe having a URI there makes sense after all.

**Comment by nikkiwd** [comment]
I thought a hash might be nicer because afaik the data wouldn't get sent to the server when loading the page that way. I'm not really bothered either way though, I just want the data available in some way. :smile:

I don't really follow why the 303 would mean it makes more sense to link to the URI.
